# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, this workflow will create VM images with Packer !

      # Runs a single command using the runners shell
      # Packer fix for backwards incompatibilities in template
      - name: Fix Packer template
        run: packer fix Win2019-IIS-Packer-withvars.json

      # Runs a single command using the runners shell
      # Packer validate
      - name: Validate Packer template
        run: packer validate Win2019-IIS-Packer-withvars.json

      # build VM image in Azure
      - name: Build Packer template
        run: packer build Win2019-IIS-Packer-withvars.json

